### ISSUE TITLE
Feature request: build Bee from source

### ISSUE THREAD

**Issue by agazso** [ethersphere/bee-factory#17]
It would be good to be able to build a Bee image from a given source tree. Maybe it's possible but I could not find out how.

The use case is when working on a new version that has not been released yet. For that it's possible to use the `latest` tag to pull from docker, but the content of that image is mutable because it is pushed from the master, therefore it cannot be reliably used to reproduce issues between different developers.

**Comment by nugaon** [comment]
> It would be good to be able to build a Bee image from a given source tree. Maybe it's possible but I could not find out how.

The scripts do not cover this use-case, as you can build your own Bee image independently from this project.
Nevertheless, your Bee image can be the base for local Bee Factory builds if you build that by `docker build . -t ethersphere/bee:$BEE_VERSION`

> The use case is when working on a new version that has not been released yet. For that it's possible to use the latest tag to pull from docker, but the content of that image is mutable because it is pushed from the master, therefore it cannot be reliably used to reproduce issues between different developers.

For the CI Docker image build workflow, the concept is always build on the released "official" Docker images, whose version can be defined by setting the `BEE_VERSION` parameter, which is the latest argument of the [manual workflow dispatch action](https://github.com/ethersphere/bee-factory/actions/workflows/publish.yaml).
You can set `true` the `The image tag will be retrieved from the bee version command` parameter as well so that the devs can differ and identify the image with exact version number.

**Comment by nugaon** [comment]
Closed by #47
